export const NUEVO_LEON_MUNICIPALITIES = [
  "Abasolo",
  "Agualeguas",
  "Los Aldamas",
  "Allende",
  "Anáhuac",
  "Apodaca",
  "Aramberri",
  "Benito Juárez",
  "Bustamante",
  "Cadereyta Jiménez",
  "El Carmen",
  "Cerralvo",
  "Ciénega de Flores",
  "China",
  "Doctor Arroyo",
  "Doctor Coss",
  "Doctor González",
  "Galeana",
  "García",
  "General Bravo",
  "General Escobedo",
  "General Terán",
  "General Treviño",
  "General Zaragoza",
  "General Zuazua",
  "Guadalupe",
  "Los Herreras",
  "Hidalgo",
  "Higueras",
  "Hualahuises",
  "Iturbide",
  "Juárez",
  "Lampazos de Naranjo",
  "Linares",
  "Marín",
  "Melchor Ocampo",
  "Mier y Noriega",
  "Mina",
  "Montemorelos",
  "Monterrey",
  "Parás",
  "Pesquería",
  "Los Ramones",
  "Rayones",
  "Sabinas Hidalgo",
  "Salinas Victoria",
  "San Nicolás de los Garza",
  "San Pedro Garza García",
  "Santa Catarina",
  "Santiago",
  "Vallecillo",
  "Villaldama",
];
